apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapplus-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snapplus-api
  template:
    metadata:
      labels:
        app: snapplus-api
    spec:
      containers:
      - name: snapplus-api
        image: 363882122270.dkr.ecr.ap-southeast-1.amazonaws.com/ptg-snapplus:v0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: snapplus-svc
spec:
  selector:
    app: snapplus-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
